Damgam Will test
beyond-all-reason/Beyond-All-Reason pull request #1799
Opened 2023-05-25 03:06 UTC by Beherrit

Cleaned up the code, made a few refactors. Made some of it easier to read as well.  Damgam will test

2023-05-25 04:03 UTC, Damgam commented
No i won't test.
@Beherith

2023-05-25 04:08 UTC, WatchTheFort requested changes
Comments that appear before global functions should be preserved, as they are used by the IDE (VSCode and maybe others) to generate the metadata to display about the function.

Try to preserve trailing commas in table entries, as it makes the code less error prone to changes, especially when reordering lines.

2023-05-25 04:08 UTC, WatchTheFort commented on common/tablefunctions.lua
> +return table
This return is not required, as the `table` table is is being mutated directly.

2023-05-25 04:08 UTC, WatchTheFort commented on common/stringFunctions.lua
> +return string
This return is not required, as the `string` table is is being mutated directly.

2023-05-25 04:08 UTC, WatchTheFort commented on common/stringFunctions.lua
Does changing the colon syntax and `self` break calling these methods on the instance itself?
```
local foo = "a,b,c,d"
local bar = foo.split(',')
```

2023-05-25 04:10 UTC, WatchTheFort commented
@Beherrit Can the pull request be given a more descriptive name than "Damgam will test"?

2023-05-25 04:11 UTC, WatchTheFort commented
Good catch on making the modoptions table local so that `Spring.GetModOptions()` doesn't perform a table copy every single time it's called.

2023-05-25 08:38 UTC, sprunk commented
> Can the pull request be given a more descriptive name than "Damgam will test"?

say no more fam

2023-05-25 14:02 UTC, WatchTheFort commented on common/springOverrides.lua
> +		return modOptionsCopy
This needs to return a new instance of the table every time it's called, otherwise one caller can mutate the results for other callers.

2023-08-13 11:54 UTC, Ruwetuin commented
I just tried this PR, models only partly show up, and that just the first thing I noticed.

inbolog also shows:
Error in Initialize(): [string "common/springUtilities/debug.lua"]:34: attempt to call field 'pack' (a nil value)

2023-08-13 11:57 UTC, Ruwetuin commented
you used table.pack(...)   isnt it just pack ?

2023-10-06 14:35 UTC, closed without merging