Fix low prio rez pull
beyond-all-reason/Beyond-All-Reason pull request #2323
Opened 2023-11-29 09:45 UTC by roberthartmann

sorry deleted the old branch by mistake

2023-12-07 21:27 UTC, sprunk commented on luaui/Widgets/gui_top_bar.lua
> +local metalCostForCommander = 1250
could take from the unit def

2023-12-07 21:27 UTC, sprunk commented on luaui/Widgets/gui_top_bar.lua
> +local addStalling = 1
this seems to only be 0 or 1, shouldn't be true/false if so?

2023-12-07 21:28 UTC, sprunk commented on luaui/Widgets/gui_top_bar.lua
> +local CMD_PRIORITY = 34571 --low prio builders
doesn't BAR have a master list of magic constants?

2023-12-07 21:29 UTC, sprunk commented on luaui/Widgets/gui_top_bar.lua
> +            glColor(0.8, 1, 0.8, 1)
check if this is in the correct place (whitespace suggests a mistake, perhaps just fix whitespace)

2023-12-07 21:31 UTC, sprunk commented on luaui/Widgets/gui_top_bar.lua
> +				local process = (r[res][1] / r[res][2]) * 13
what's the significance of the 13? could use a comment or a named constant

2023-12-07 21:32 UTC, sprunk commented on luaui/Widgets/gui_top_bar.lua
> +            if commands[i].id == CMD or commands[i].id < 0 then
`CMD` is a table so the numerical id will never be equal to it, should be `CMD.SOMETHING`

2023-12-07 21:58 UTC, roberthartmann commented on luaui/Widgets/gui_top_bar.lua
> +        if #totalReservedBPData > 30 then
10 time steps of 15 game frames

2023-12-07 22:10 UTC, MasterBel2 requested changes
Looking pretty good, most comments are pretty minor things with a bunch of repeated concerns. Should hopefully be quick and easy to clean up

2023-12-07 22:10 UTC, MasterBel2 commented on luaui/Widgets/gui_top_bar.lua
> +		if res == 'energy' then
Spaces

2023-12-07 22:10 UTC, MasterBel2 commented on luaui/Widgets/gui_top_bar.lua
> +local shareIndicatorArea = { metal = {}, energy = {}, BP = {} } --get rid of BP
This comment is confusing

2023-12-07 22:10 UTC, MasterBel2 commented on luaui/Widgets/gui_top_bar.lua
> +local relXpos = 0.25 -- ooo 0.3
Unhelpful comment; either elaborate or remove?

2023-12-08 07:58 UTC, thehobojoe commented on luaui/Widgets/gui_top_bar.lua
> +            if isFactory == 0 then
I think being more verbose in this case is probably good, it's subjective but I find the current pattern more readable, I would just do 
`local isFactory = unitDef.isFactory or false` to keep it neater

2023-12-08 08:11 UTC, thehobojoe commented
Since you've already received very detailed code review I'll just leave a higher level comment. While this new bar is very neat, not everyone is going to want it, and it needs to be configurable, there are two ways this could be achieved:

1. Simply put in a toggle. This can start with just a boolean in the file while you put it together, making sure everything is as it was before with this toggle set to false, once that's working you would need to add a flag to the settings somewhere to enable it. I know you're new to programming so this probably feels daunting, but don't be afraid to ask questions during the process. This has downsides however, not only will this widget simply have more complex code and be harder to parse, but it will also (marginally, granted) add performance overhead.
2. Make it a separate widget. This will be harder, but will be much more maintainable in the long run. The logic will be much easier to follow, turning it off will reduce loading and runtime overhead, and future changes and improvements will be much easier to make. To do this you'd want to follow patterns that you can see in lots of other widgets e.g. gridmenu https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/gui_gridmenu.lua#L707
It responds to calls from other widgets by this method, allowing you to dynamically change what the widget does based on calls from other widgets, settings and so on. So to do this, you'd want to add one or more API functions into top_bar following this pattern, like e.g. `includeBuildBar` which would shift sizes/placements of a couple of the features in top_bar, and nothing more, and then your external `build_bar` widget would render itself in the space you just made by doing that.

Which approach you take is your decision, and though #2 will likely take more work, it's the one I would recommend.

2023-12-08 11:12 UTC, roberthartmann commented
I see the second version is cleaner. That is true.
I have allready made it toggable, but, eventhough I was *sure* that I did everything right do upload it... I didn't. That is why you still saw the old version without it.

Never the less it is now existing that way and I guess it still could be a good thing in a way: a POC is now existing. How to pull apart the widgets in detail is now easier than ever... BUT the metal and energy bars use so much info to calculate the real pull of resources, while being on low prio I think this calculation needs to be in a separate lua to provide the values to both top bars or the top bar needs to give the info to the BP bar.

What do you think? 

For me it feels like: just let the three bars together, they are using sooo much of the code together anyways.

2023-12-09 00:53 UTC, thehobojoe commented
Yeah if there's a lot of code sharing it makes sense to keep it together, so long as the toggle works and it is hooked up to settings. You can use this as a reference for how to wire this up to the settings https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2283/files

2023-12-22 09:42 UTC, closed without merging