feat(synced_proxy): add synced proxy gadget for running code in synced
beyond-all-reason/Beyond-All-Reason pull request #2624
Opened 2024-02-17 06:25 UTC by salinecitrine

To call a function, call `Spring.SendLuaRulesMsg(prefix .. fn)`, where the prefix is from synced_proxy.lua, and `fn` is serialized with an RPC object (rpc.lua).

The return value of the function can be accessed by `widget:RecvLuaMsg()`, where the message is composed of the return prefix from synced_proxy.lua, and a serialized return value, which can be deserialized with the same RPC object (rpc.lua).

When a function is serialized or deserialized, a `returnID` is used to correlate function calls with their associated returns. This must be checked to make sure that `widget:RecvLuaMsg()` is looking at the desired return.

---
This is intended for use with the new test runner.

The serpent library can be found at https://github.com/pkulchenko/serpent

2024-02-19 21:31 UTC, Beherith requested changes
To be on the safe side, make sure that code can only be executed if Spring.Utilities.Gametype.IsSinglePlayer() is true. This generally isn't perfect either, because IsSinglePlayer only checks for playercount == 1, so spectators, who can send luarules messages can be present

2024-02-19 21:45 UTC, Beherith commented
Also check if cheating is on!

2024-02-20 02:41 UTC, salinecitrine commented
> To be on the safe side, make sure that code can only be executed if Spring.Utilities.Gametype.IsSinglePlayer() is true. This generally isn't perfect either, because IsSinglePlayer only checks for playercount == 1, so spectators, who can send luarules messages can be present

> Also check if cheating is on!

Done!

2024-02-22 21:15 UTC, Beherith commented
Excellent, remind me to discuss and merge this this weekend!

2024-03-04 09:42 UTC, merged