Add Levenshtein distance functions to string lib
beyond-all-reason/Beyond-All-Reason pull request #3648
Opened 2024-08-29 08:42 UTC by Beherith

```	
--- Calculates edit distance of two strings, O(n*m) time, O(n) memory
	---@param a string
	---@param b string
	---@return number 

	function string.Levenshtein(a,b)
```
```
	--- Finds string that is closest to a in a table
	---@param a string
	---@param t table, primarily values are strings, keys can be strings too
	---@return string, number bestresult, bestscore
	function string.FindClosest(a,t)
```

2024-09-06 06:08 UTC, salinecitrine requested changes
What's the use case for this? Probably worth mentioning in the PR description.

2024-09-06 06:08 UTC, salinecitrine commented on common/stringFunctions.lua
> +		return Levenshtein1[lenb]
The function gives incorrect output for at least these test cases:
```lua
{
	name = "returns the length of the non-empty string for one empty string",
	args = { "", "apple" },
	expected = 5,
},
{
	name = "returns the length of the non-empty string for one empty string (reverse case)",
	args = { "apple", "" },
	expected = 5,
},
{
	name = "returns 1 for strings differing by one character",
	args = { "apple", "appla" },
	expected = 1,
},
{
	name = "returns the length of the longer string for completely different strings",
	args = { "cat", "dogs" },
	expected = 4,
},
```
This change fixes those tests:
```suggestion
		return Levenshtein0[lenb + 1]
```

2024-09-12 20:29 UTC, WatchTheFort commented
@Beherith What is the status of this?

2024-10-27 14:44 UTC, salinecitrine requested changes

2024-10-27 14:44 UTC, salinecitrine commented on common/stringFunctions.lua
> +	function string.Levenshtein(a,b)
```suggestion
	function string.levenshteinDistance(a,b)
```

2024-10-27 14:44 UTC, salinecitrine commented on common/stringFunctions.lua
> +				local distance = string.Levenshtein(a, b)
```suggestion
				local distance = string.levenshteinDistance(a, b)
```

2024-11-21 20:08 UTC, WatchTheFort commented
@Beherith Is this ready to merge?

2025-01-02 20:07 UTC, WatchTheFort commented
@Beherith Is this ready to merge?

2025-01-11 19:26 UTC, salinecitrine approved these changes
tests pass

2025-01-11 19:26 UTC, salinecitrine commented on common/stringFunctions.lua
> +	function string.FindClosest(a,t)
```suggestion
	function string.findClosestString(a,t)
```

2025-03-13 20:05 UTC, WatchTheFort commented
@Beherith What is the status of this PR?

2025-03-14 01:51 UTC, sprunk commented
I think the status is "prove me wrong it's not completely abandoned by reopening it"

2025-03-14 01:51 UTC, closed without merging