Legion Hover Constructor added
beyond-all-reason/Beyond-All-Reason pull request #3988
Opened 2024-12-01 20:32 UTC by EnderRobo

### Work done
Created the Legion Hovercraft Constructor model, script and unitpic.

![Screenshot 2024-12-01 135508](https://github.com/user-attachments/assets/e69cffa1-936e-4c86-be5d-e04f94589d4b)

2024-12-07 15:40 UTC, robertthepie requested changes
Can't Load anims as they are in the wrong folders

2024-12-07 15:40 UTC, robertthepie commented on objects3d/Units/legch_clean.cob
Wrong Folder

2024-12-07 15:40 UTC, robertthepie commented on objects3d/Units/legch_clean.bos
Wrong Folder

2024-12-07 18:57 UTC, EnderRobo commented on objects3d/Units/legch_clean.cob
Fixed.

2024-12-07 18:57 UTC, EnderRobo commented on objects3d/Units/legch_clean.bos
Fixed.

2024-12-07 19:17 UTC, robertthepie approved these changes

2024-12-12 20:29 UTC, drivver44 commented
can i be added to the PR reviewers?

2024-12-14 21:09 UTC, merged

2024-12-20 00:04 UTC, ZephyrSkies7 commented
@EnderRobo does this still need a unitpic?