Standardize Factory Footprint Sizes
beyond-all-reason/Beyond-All-Reason pull request #3997
Opened 2024-12-05 03:33 UTC by Tharsy

This Changes almost every factory in the game; exceptions are factories that don't need changes. 
This makes factories follow a standard size for their tier. The idea of this is to balance the surface area usage between all factions while also allowing the factories to be big enough to support the units they build, however, extended to every factory to fit the following:
T1 = 6x6,
T1 Air = 6x9,
T2 = 9x9,
T3 + T2 Shipyard = 12x12

Notable changes are:
- T2 factories are now bigger.
- Gantries are bigger and some t1 factories are smaller, but all now align with the grid.
- Armada no longer has smaller labs overall.
- The cortex gantry can fit the Behemoth now!
- The dragon fits in it's factory now.

### Work done
- Rescaled models
- New models for cortex gantry and t2 air plants.
- Updated scripts for the new Cortex Gantry and Armada Air Plant
- Updated unit pictures for some units
- Updated yard maps

### Screenshots:
In the examples below the grid squares on the map are a 3x3 footprint.
![image](https://github.com/user-attachments/assets/b14568e8-5663-4546-9ef2-97197ebd004d)
![image](https://github.com/user-attachments/assets/27009ebc-3d4a-476a-a0bf-23640a0d0b37)

![armaap](https://github.com/user-attachments/assets/ee61f0a1-e3d2-4cd6-9315-42b93c8a5a5d) ![coraap](https://github.com/user-attachments/assets/49311645-9810-47de-9888-257077912e85) ![coralab](https://github.com/user-attachments/assets/d4f30587-026f-49a6-917a-533e8c07659c) ![corgant](https://github.com/user-attachments/assets/c135318a-c50f-48dd-9f6d-15db0f26f992)

### Work needed
- Sanity check on unit colvols and yardmaps
- Help making AO-plates for each unit

2024-12-05 21:58 UTC, WatchTheFort approved these changes

2024-12-08 09:23 UTC, drivver44 requested changes
hitbox adjustment can be scaling and offset issue
hitbox scaling just means that the hitbox isnt scaled to the model

floating hitbox means that the hitbox does not intersect the ground

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/legalab.lua
hitbox needs adjustment

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/legvp.lua
floating hitbox

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/legap.lua
> +		footprintz = 6,
not 6x9z as listed in the PR standards
`T1 Air = 6x9,`
hitbox needs adjustment as its smaller than the model

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/legamsub.lua
hitbox is significantly bigger than the model

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/legavp.lua
hitbox needs adjustment
also the model seems off to what the footprint grid should be
the model is slighly off on the sides

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/leggant.lua
hitbox is bigger than model and footprint occupancy

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/leggant.lua
>  		usepiececollisionvolumes = 1,
remove this line
also add hitbox to the unitdef

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/leglab.lua
> +		yardmap = "yooooy oooooo coccoc occcco occcco yccccy",
remove `y` and replace with `o`
IMO this goes against the standardization your trying to achieve
yes there is a ruling on the footprint occpancy question. i think in this case that ruling should be ignored

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/leghp.lua
hitbox needs adjustment

2024-12-08 09:23 UTC, drivver44 commented on units/Legion/Labs/legjim.lua
needs hitbox adjustment

2024-12-12 20:17 UTC, drivver44 commented on units/CorBuildings/LandFactories/coraap.lua
> +		collisionvolumescales = "128 42 128",
this hitbox is still not occupying the full model and the hitbox does not intersect the ground

2024-12-12 20:34 UTC, drivver44 commented on units/ArmBuildings/LandFactories/armaap.lua
> +		yardmap = "yyyoooyyy yoooooooy yoooooooy ooooooooo ooooooooo ooooooooo ooooooooo yoooooooy yyoooooyy",
this should be entirely `o`
if the hitbox occupies the spot so does the footprint
convert the hitbox shape to from `CylY` to box

2024-12-12 20:34 UTC, drivver44 commented on units/Legion/Labs/legaap.lua
hitbox does not line up with the coraap hitbox

2024-12-12 20:34 UTC, drivver44 commented on units/ArmBuildings/LandFactories/armalab.lua
model is slightly bigger than hibox and footprint occupancy

2024-12-12 20:34 UTC, drivver44 commented on units/ArmBuildings/SeaFactories/armshltxuw.lua
model is bigger than occupied area

2024-12-12 20:34 UTC, drivver44 commented on units/ArmBuildings/SeaFactories/armasy.lua
hitbox does not line up wioth footprint or model occupancy

2024-12-12 20:34 UTC, drivver44 commented on units/CorBuildings/LandFactories/coralab.lua
> +		collisionvolumescales = "140 56 136",
hitbox does not line up with footprint

2024-12-12 20:34 UTC, drivver44 commented on units/CorBuildings/LandFactories/corgant.lua
> +		yardmap = "yyooooooooyy oooooooooooo oooooooooooo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo yoccccccccoy",
should be exclusive `o`
if the hitbox occupies a spot so does the footprint

2024-12-12 20:35 UTC, drivver44 commented on units/CorBuildings/LandFactories/coraap.lua
> +		collisionvolumescales = "140 42 140",
sanity comment 
floating hitbox

2024-12-12 20:37 UTC, drivver44 commented on units/CorBuildings/LandFactories/coravp.lua
> +		yardmap = "yoooooooy ooooooooo ooooooooo oocccccoo oocccccoo oocccccoo oocccccoo oocccccoo oocccccoo",
`Y` should be `O`

2024-12-12 21:01 UTC, drivver44 commented on units/ArmBuildings/SeaFactories/armshltxuw.lua
still needs adjusment

2024-12-12 21:01 UTC, drivver44 commented on units/ArmBuildings/SeaFactories/armshltxuw.lua
![Uploading image.png…]()

2024-12-12 21:04 UTC, drivver44 commented on units/ArmBuildings/LandFactories/armap.lua
> +		yardmap = "yoooooooy ooooooooo ooooooooo ooooooooo ooooooooo yoooooooy",
`y` to `o`

2024-12-12 21:04 UTC, drivver44 commented on units/Legion/Labs/legavp.lua
> +		yardmap = "yoooooooy ooooooooo ooooooooo oocccccoo oocccccoo oocccccoo oocccccoo oocccccoo oocccccoo",
`y` to `o`

2024-12-12 21:04 UTC, drivver44 commented on units/Legion/Labs/leggant.lua
> +		yardmap = "yyooooooooyy oooooooooooo oooooooooooo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo ooccccccccoo yoccccccccoy",
`y` to `o`

2024-12-12 21:11 UTC, drivver44 commented
safe to merge
any issues that come up are my fault and ill fix @WatchTheFort

2024-12-12 21:24 UTC, merged