Daedalus Colvol/Hitbox Adjustments
beyond-all-reason/Beyond-All-Reason pull request #4091
Opened 2024-12-31 20:58 UTC by ZephyrSkies7

### Work Done
Daedalus (`legerailtank`) hitboxes have been adjusted and fixed thanks to @drivver44's support.

Carries on from #4089.

### Work Needed
- [] Needs review from Code Review team on this PR and #4089 as well.

2025-01-02 04:50 UTC, drivver44 requested changes
the unit spacing will be resolved in a seperate PR as the thor has the same exact issue

2025-01-02 04:50 UTC, drivver44 commented on luarules/configs/collisionvolumes.lua
> +	['0']={83.6,27.3, 85.6,0,1,-3, 2,1},
X volume sizing can be reduced down a bit
the hitbox needs some offset going backwards for the Z axis

2025-01-02 04:50 UTC, drivver44 commented on units/Legion/T3/legerailtank.lua
the wreck hitbox is wrong
its not wide enough nor is it tall enough
it also floats above the ground

2025-01-03 02:36 UTC, ZephyrSkies7 commented on units/Legion/T3/legerailtank.lua
fixed

2025-01-03 02:36 UTC, ZephyrSkies7 commented on luarules/configs/collisionvolumes.lua
> +	['0']={83.6,27.3, 85.6,0,1,-3, 2,1},
fixed

2025-01-03 03:10 UTC, merged